/*
COSAS PARA AGREGAR Y RESOLVER:
AGREGADO 1) Tabla de Entrenador con datos como nombre, apellido, usuario, nivel, telefono, nacionalidad, 
AGREGADO 2) Tabla de Torneos: nombre de torneo, fecha de torneo, horario, localidad, locacion, organizado por
AGREGADO 3) Tabla de Registro a torneos: donde se muestre que entrenador se registro en cada torneo
AGREGADO 4) Tabla de Registro de equipo: donde se muestren los 6 pokemon de cada entrenador que registro para cada torneo (cada pokemon tiene que tener un ataque rapido y dos cargados)
5) Tabla de Resultado de torneos: donde muestre las posiciones de cada entrenador en cada torneo
AGREGADO 6) agregar a la tabla de equipo pokemon la columna de puntos de combate de cada pokemon (max 1500) 
7) a la tabla de equipo fijate de como poner para que no se repitan los id_pokemon
8) podrias agregar una tabla que muestre cuantos puntos de campeonato suma cada posicion en cada torneo 
9) a la tabla de torneos podrias agregar una columna para diferenciar el tipo de torneo (regiona, invitacional, etc), cada tipo de torneo otorga una cantidad de puntos de campeonato diferente (relacionala con la tabla del punto 8)
10) modificar los ataques de los pokemon en "Insercion_equipos". Actualmente no son correctos.
11) fijate de mejorar la resolucion del diagrama.
12) cuando tengas tiempo revisa mejor la ortografia.
13) problema con la tabla de equipos, te genero un id por cada entrada, cuando deberia ser el mismo id para los 6 pokes del equipo.
*/